WIP

diff --git a/.github/actions/ruff/action.yml b/.github/actions/ruff/action.yml
--- a/.github/actions/ruff/action.yml
+++ b/.github/actions/ruff/action.yml
@@ -5,4 +5,5 @@ runs:
   steps:
    - shell: /bin/bash
      run: |
-      echo "RUFF!"
+       pip install ruff
+       ruff check --fix . || echo "FAILED=ruff" >> "$GITHUB_OUTPUT"
